version: "3.7"

services:
  postgresql-database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fin_api

volumes:
  postgresql_data:
    driver: local
